<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use App\Models\Role;

class UserSeeder extends Seeder
{
    public function run()
    {
        $users = [
            [
                'name' => 'Abang Sales',
                'email' => 'sales@gmail.com',
                'password' => Hash::make('password'),
                'role_id' => Role::where('name', 'Staff')->first()->id,
            ],
            [
                'name' => 'Ibu Finance',
                'email' => 'finance@gmail.com',
                'password' => Hash::make('password'),
                'role_id' => Role::where('name', 'Finance')->first()->id,
            ],
            [
                'name' => 'Manager',
                'email' => 'manager@gmail.com',
                'password' => Hash::make('password'),
                'role_id' => Role::where('name', 'Manager')->first()->id,
            ],
            [
                'name' => 'Pak Direktur',
                'email' => 'direktur@gmail.com',
                'password' => Hash::make('password'),
                'role_id' => Role::where('name', 'Director')->first()->id,
            ],
            ["name"=>"Ayesha","email"=>"ayesha@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Afinsa Dheanisa","email"=>"afinsa.dheanisa@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Eka Fakhrama Putra","email"=>"ekafakhramaputra@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ratu Annisa Wulan Andini","email"=>"ratu.annisawulan@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Suci Rohmayni","email"=>"sucirohmayni@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Dior Alexandros Lowhorn","email"=>"dalowhorn@usfca.edu","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Julius R Bowie Jr","email"=>"jbowie20@yahoo.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Peni Iswarini","email"=>"peni.iswarini@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Gladvisca Vlaviory Lumingkewas","email"=>"gladviscavl@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Fakriza Ahmad","email"=>"fakriza.ahmad@khazanahalwahda.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ni Wayan Kunir","email"=>"niwayan.kunir@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Nengah Wariati","email"=>"nengah@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ni Nyoman Sumariani","email"=>"ninyoman.sumariani@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ni Nyoman Srimin","email"=>"ninyoman.srimin@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"I Ketut Arna","email"=>"iketut.arna@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"I Wayan Eka Yasa","email"=>"iwayan.eka@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"I Made Suargita","email"=>"imade@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Sutarsan","email"=>"sutarsan@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ida Bagus Made Oka Suarjana","email"=>"idabagusmade.oka@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"I Ketut Karjaya","email"=>"iketut.karjaya@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"I Ketut Suantika","email"=>"iketut.suantika@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Yabes Tanuri","email"=>"yabes@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Michael Immanuel Gerald","email"=>"michael.gerald@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ni Made Sartika Ningsih","email"=>"sebetuksaudara@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Roy Pradipta","email"=>"roy.pradipta@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Putri Paramita Sudali","email"=>"putri.sudali@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ervi Ho","email"=>"ervi.ho@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ketut Suniata","email"=>"ketutsuniata72@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Erwyn Prasetyo Dwianto","email"=>"ewin.setyo@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Katharine Wianna","email"=>"katharine.wianna@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Deasy Nathalia","email"=>"deasy.nathalia@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"I Wayan Swastika","email"=>"wayanswastika999@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ahmat Nehru","email"=>"ahmat.nehru@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Anggi Saputra","email"=>"anggi.saputra@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ahmad Arkan","email"=>"ahmad.arkan@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Fitroh Abdul Malik","email"=>"fitroh.malik@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Risha Adi Widjaya","email"=>"risha.widjaya@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Richi Kurniawan","email"=>"richie.kurniawan@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Gita Adhiprakoso Suwondo","email"=>"gita.suwondo@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Genta Perdana","email"=>"genta.perdana@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Yossi Adityawarman","email"=>"yossi.rasjad@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Budhi Aprilianto Saputra","email"=>"budhi.saputra@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Iwan Setiawan","email"=>"iwan.setiawan@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Julianus Doan","email"=>"julianus@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Paidi Hidayat","email"=>"paidi.hidayat@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Kukuh Bangkit Maryono","email"=>"kukuh.maryono@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Yoga Aji Sutopo","email"=>"yoga.sutopo@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Tri Budiman","email"=>"tri.budiman@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Melinda Novia Lamora","email"=>"melinda@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ni Kadek Oka Aryanti","email"=>"oka.aryanti@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Kadek Ari Sukmantara","email"=>"ari.sukmantara@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Bagus Kurniawan","email"=>"bagus.kurniawan@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Efin Retno Safitri","email"=>"efin.safitri@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Lusiana Susanto","email"=>"lusiana.susanto@baliutd.com","role_id"=>Role::where('name','Manager')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Yohanes Riza Priyantho","email"=>"yohanes.riza25@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Yosef Deny Pamungkas","email"=>"yosef.pamungkas@bolanusantara.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ni Luh Desyantari","email"=>"luhdesyantari03@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Daniel Rinekso Nugroho","email"=>"danielforzha@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Made Ayu Budimeliani","email"=>"melianiayu9@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ida Bagus Yoni Diatmika Sutha","email"=>"idabgs.yonidiatmika@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Sugiantoro","email"=>"sigit.sugiantoro@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Firdaus Kukuh Pramana JP","email"=>"vpratama7717@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Zulfikar","email"=>"joelslank639@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"I Komang Astawa","email"=>"komangastawa220396@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ambariza Barkah","email"=>"ambariza.barkah@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Silvia Magdalena Simanjuntak","email"=>"silvia.magdalena@baliutd.com","role_id"=>Role::where('name','Director')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Mahfud Sidik","email"=>"sidikmahfud259@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Nico Namapribowo","email"=>"nico.namapribowo@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Deo Wanda","email"=>"deo.wanda@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Elvandy Cheristea","email"=>"elvandy.cheristea@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Muhamad Baresi","email"=>"muhamad.baresi@unitedcreative.co.id","role_id"=>Role::where('name','Manager')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Veronica Mutiana","email"=>"veronica.mutiana@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Musha","email"=>"mushatefa702@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Angga Anggriawan","email"=>"angga.anggriawan@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Vino Agustian Pratama Putra","email"=>"vincoboy94@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Govindo Gogi Kumala","email"=>"govindo.gogi@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Yohanes Ade Bunian Moniaga","email"=>"yohanes.ade@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Achmad Haidar","email"=>"achmad.haidar@bolanusantara.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Dimas Muchli Erlambang","email"=>"dimas.muchli@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Robin Suparto","email"=>"robin.suparto@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Dwi Ramadhan Seto","email"=>"seto@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"M. Ikhsan Apridho","email"=>"ikhsan.apridho@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Mohamad Irvans Zulisando","email"=>"irvans.zulisando@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Dwi Kurniasih","email"=>"dwi.kurniasih@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Eko Setiafan","email"=>"eko.setiafan@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Elsa Susanto","email"=>"elsasusanto@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Anang Wahyudi","email"=>"anang.wahyudi@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Galih Seta Dananjati","email"=>"galih.dananjati@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Elsa Ardyta","email"=>"elsa.ardyta@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ni Kadek Yuliantari","email"=>"kadek.yuliantari@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Made Rista Dewi","email"=>"made.rista@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Yo El Andreano","email"=>"yoel.andreano@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ade Sudrajat","email"=>"adelsoedrajat@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Syabani Mutohir","email"=>"baniutd0807@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Muhamad Yofi Fauzi","email"=>"yofi.fauzi@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Panji Nurimanto","email"=>"panji.nurimanto@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Wildan Rizaluddin Fadhlulloh","email"=>"wildan.rizaluddin@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ayu Hani Listiasari","email"=>"ayu.hani@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Erma Nurjanah","email"=>"erma.nurjanah@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Dion Dominicus Niti Waluyo","email"=>"dion.nitiwaluyo@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Gregorius Charvin Gardhaputra","email"=>"charvin.avin@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Mohamad Fahmi","email"=>"mohamad.fahmi1121@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Tanjung Anom Wijaya","email"=>"tanjungwijaya41@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Andhikaputri Himawan","email"=>"dhika.himawan@unitedcreative.co.id","role_id"=>Role::where('name','Manager')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Putu Desy Primayanti","email"=>"desy.primayanti@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Daniel Oktavianus","email"=>"daniel@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"I G N Teguh Putra Negara","email"=>"ignteguh.putra@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"I Gusti Ngurah Rustawijaya","email"=>"igusti.ngurah@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Agnes","email"=>"agnes.odelia@unitedcreative.co.id","role_id"=>Role::where('name','Manager')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Irvine Kurniawan","email"=>"irvine@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"I Putu Bagus Arya Candra Putra Perdana","email"=>"iputubagusarya.candra@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ponsianus Nyoman Indrawan","email"=>"ponsianus.nyoman@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Rico Aditya Suharno Putra","email"=>"rico.adityasuharno@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Surliyadin","email"=>"surliyadin@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Lutfi Alfian Eka Koswara","email"=>"lutfialfian.eka@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Yahya Safudin","email"=>"yahya@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Alfian Indrayuda","email"=>"alfian@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Muhammad Rizki","email"=>"muhamad.rizki@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Andi Melati Andarwati Octavia","email"=>"amelati.octavia@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Nia Maelani H","email"=>"niamaelani@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Diandra Nabila","email"=>"diandra.nabila@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Haefa Muhammad Azhar","email"=>"haefa.azhar@unitedcreative.co.id","role_id"=>Role::where('name','Manager')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Sabrina","email"=>"sabrina@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Gamma Abdurrahman Thohir","email"=>"gammathohir123@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Alexander MP Oemanas","email"=>"alexander.putra@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"I Nyoman Subagia","email"=>"inyomansubagia120@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Dera Kariema","email"=>"dera.kariema@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Andre Leo","email"=>"andre.leo@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Rosa Priskila Sitanggang","email"=>"rosa.priskila@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Yogyanto Edi Soedharsono","email"=>"yogyanto.es@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Nouval Kemalsyah Adhigumilang","email"=>"nouval.kemal@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Agustino Jonathan","email"=>"agustino.jonathan@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Bonatio Michael Partogi","email"=>"bonatio.michael@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Riselda Rahma Annisa Lalusu","email"=>"riselda.lalusu@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Rahmanita Aulia","email"=>"rahmanita.aulia@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Adelle Odelia Tanuri","email"=>"adelle@rahasiagadis.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Namira Albay","email"=>"namira.albay@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Annabella Clarissa Putri Ginting","email"=>"bella.clarissa@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Lidya Wulandari","email"=>"lidya.wulandari@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"A.A Gede Agung Bagus Paramesvara","email"=>"paramesvara10@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Neo Putu J Satria Pande","email"=>"putuneo05@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Muhamad Furqon","email"=>"moe.furqon@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Maria Lynch","email"=>"maria@rahasiagadis.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Muhammad Muhtar Amri","email"=>"muhtar.amri@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ida Bagus Komang Adhi Widyacaya","email"=>"gusmank21@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Riean Fairuz Zahran","email"=>"riean.fz24@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Tommy Satria Ishar","email"=>"thomzkids1@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ardina","email"=>"ardina@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Asep Nugroho","email"=>"suja18sc@hotmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Abraham Renoldi Wenas","email"=>"abrahamwenas.bisnis@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Handri Satrya Santosa","email"=>"satria_handri@yahoo.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Alkristian Candra","email"=>"alkristian_chandra@yahoo.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ajudan Septiadiyasa","email"=>"tudecopo14@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Umar Shaufy","email"=>"umarshaufy90@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Frida Adestya","email"=>"adestyafrida@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Fitriyani Karlina","email"=>"fina.karlina@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Yulia Andita Sari","email"=>"yulia.andita@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Aryani Siti Wedyaningsih","email"=>"aryani.siti@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Yehezkiel Tarnama H.S","email"=>"yehezkiel.siahaan@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Bagas Aji Syaputra","email"=>"bagas.syaputra@bolanusantara.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Mario Chandra Putra","email"=>"mario.chandra@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Catharina Martha Ulina","email"=>"catharina.martha@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Muhamad Rachmat Akbar","email"=>"rachmat.akbar@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Misrin Efendi","email"=>"efendimisrin@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Agung Febriana","email"=>"agung.fjavan12@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Renato Adhitama","email"=>"renato.adhitama@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Dhimas Odietama Putra","email"=>"dimas.odhietama@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Anang Setiaji","email"=>"setiaji.anang@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Achmad Juliansyah","email"=>"ahmadjlnsyh@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Octiana Ibranda","email"=>"octiana.ibranda@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Muhammad Firdan Ghifari","email"=>"Firdanghifari153@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Adelina Santika Azzahra","email"=>"adelinas.azzahra@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Muhammad Heri Pradana","email"=>"heripradana31@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Rokhim","email"=>"gorokhim@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Hermansah","email"=>"hermansah@khazanahalwahda.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Gina Aulia Taqwa","email"=>"gina.taqwa@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Arief Rahman","email"=>"ar200493@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ani Rahmawati","email"=>"ani.rahmawati@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"M Rakha Rizky","email"=>"rakha.rizky@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Gadis Denissa Novianto","email"=>"gadis.denissa@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Alief Maulana","email"=>"alief.maulana@bolanusantara.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ricard Gunawan","email"=>"richard.gunawan@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"I Kadek Astawan","email"=>"kadek07683@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Made Indra Novrihadi","email"=>"made.indra@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Clarissa Julia Scolastica","email"=>"clarissa@rahasiagadis.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"I Komang Artayasa","email"=>"ikomangartayasa791@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"I Gusti Lanang Eka Saputra","email"=>"lanangeka82@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ketut Sukiani","email"=>"sukistart@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ida Ayu Ketut Ari Widiastuti","email"=>"ariwidiastutiidaayu@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"I Putu Agustia Arianca","email"=>"agusarianca@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ryan Choirul Makkih","email"=>"ryan.choirul@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"I Made Angga Wicaksana Yasa","email"=>"angga.wicaksana@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Yessica Anastasya","email"=>"anastasyasamel@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Muhammad Akbar Zea Rezky Ramadhan","email"=>"akbar.zea@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Asiva Fazriyah","email"=>"asiva.fazriyah@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            // ["name"=>"Maheza Prasetya","email"=>"hadisofyan3177@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Moh Fristo Rizky Linanggeng","email"=>"muhammad.fristo@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Fakhrurrizal Rahmawan","email"=>"rizal.rahmawan@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"I Wayan Arik Sukmadinata","email"=>"ariksukmadinata18@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Jenny Ima Simon","email"=>"jenny.ima@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Putri Kartika Apriyanti","email"=>"putri.krtk77@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Nurul Puspitasari","email"=>"nurul.puspita22@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Rizky Ardyas Ramadhan Putra","email"=>"rizky.ardyas@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Dewi Anggreni Girsang","email"=>"dewi.anggreni@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Dita Rizkiani","email"=>"dita.riskia@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Rokhmad Joko Santoso","email"=>"rokhmad.santoso@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Czeivand Al Lazuardi","email"=>"al.czeivand@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Muhammad Taufiq Alwan Naufal","email"=>"taufiq.alwan@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Yuddy Marcelino Tambaritji","email"=>"yuddy.marcelino@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Muhammad Fadillah Juliantara","email"=>"fadillah.juliantara@khazanahalwahda.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Citra Oktarry","email"=>"citra.oktarry@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Sri Cendrawasih","email"=>"sricendrawasih95@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ari Permana Sudarto","email"=>"arybolang228@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Adella Putri Macharani","email"=>"adella.macharani@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Fatimatuzzahro","email"=>"fatima.tuzzahro@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Yona Andini Amsah","email"=>"yona.amsah@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"I Gede Murah Sukarsa Jana","email"=>"gedepenyu@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Yandi Yahya Isnain","email"=>"yandi.isnain@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ajeng Saskitasari","email"=>"saski@rahasiagadis.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"I Made Prima Adi Prasastha","email"=>"primaprasastha@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Komang Nika Tri Swarantika","email"=>"nikojr04@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Rikuang","email"=>"rikuang.hong@baliutd.com","role_id"=>Role::where('name','Manager')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Muhammad Miladi Akmal","email"=>"guarovansuaf@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Terry","email"=>"terry@teltics.com","role_id"=>Role::where('name','Manager')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Muhammad Admiraldi Mahardhika Putra","email"=>"muhammad.admiraldi@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Sarah Tiari","email"=>"sarah.tiari@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Hanifah Puspitasari","email"=>"hanifah.puspitasari@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"I Kadek Surya Ardiantara","email"=>"suryaardiantara1@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Jasmine Eliza Syaima Hakiki","email"=>"jes.hakiki@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Christine Natalia","email"=>"christine.natalia@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Nadine Tomharto","email"=>"nadine.tomharto@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Rai Augia Pribadi","email"=>"dimmyathaya@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Gede Elgi Wimbardi","email"=>"gedeelgi90@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Rendy Harsono Pranata","email"=>"rendy.harsono@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Riddo Tandian","email"=>"riddo.tandian@gmaill.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Trifika Prihartanto Wijaya","email"=>"Trifika.p@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Clarissa Angelica","email"=>"clarissa.angelica@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Eka Fenty Widyandari","email"=>"fenty.eka@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Daffa Kesuma Putra Dharma","email"=>"daffakesumaputra@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Natia Adly","email"=>"Natia.adly@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Viky Rumaniogi","email"=>"vikyrmn95@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Indarman Zen","email"=>"indhenk@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Moehammad Alfa Virgiansyah","email"=>"alfa24.av@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Komang Saritami","email"=>"komangami24@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Sucahyo Ramdhoni","email"=>"cahyoram@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Muhammad Fariz","email"=>"farizsanusirowi.fsr@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Yoshua Ericson","email"=>"yoshuaericson@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Mo Arifin Somadani","email"=>"somadani2@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Hendra Sembiring","email"=>"beingmostwanted@yahoo.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Raden Roro Ratna Indah Wulandari","email"=>"wd.ratnaa@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Alvian Mushafy Abdullah","email"=>"ian21uiux@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Salma Aulia Nazhifah","email"=>"salmanazhifah14@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Gregorius Pramudya Anindito","email"=>"23pramudyaanindito@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Faishal Hafizh Dhau","email"=>"Fhd.isal@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Lafa Shidqi","email"=>"Lafashidqi83@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Edi Jaenuri","email"=>"edijaenuri909@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Yulisma Septriani","email"=>"lisaholiday1309@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Yusuf Irfan Fauzi","email"=>"fauziyusufirfan@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Edward Yopiedo Oktario","email"=>"piedoktario@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Syarifuddin","email"=>"arifsyarifuddin46@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ni Komang Diah Ratna Sari","email"=>"diahratna529@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Jeremy Krisnugroho","email"=>"jeremykrisnugroho@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Sofyan Hadi","email"=>"hadisofyan3177@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Acep Supriadi","email"=>"acep.supriadi99@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Gerre Martin Bungai","email"=>"gerremartin88@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Meggah Tri Sakti","email"=>"megahtrisakti@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Aqshal Akbar Yaasiino","email"=>"aqshalakbar72@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Anthony Garbelotto","email"=>"anthony@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"I Ketut Mergan Suarjaya","email"=>"taridewi09@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Yusuf Firdaus","email"=>"yusuf@baliutd.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"RA Fitriyani Akasah","email"=>"vinnieakasah@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ahmad Dorojatun","email"=>"dorojatunahmad@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Atqiya Sajidah Ibadurrahman","email"=>"atqiyas@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Jacques Rachman Pradana","email"=>"jacquesrahman2185@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Suprapdi","email"=>"praptosiwa0111@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Geri Stevanus Korompis","email"=>"gerrygendut@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ni Ketut Tri Anitaningsih","email"=>"tuttri48@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Pricho Bramantheo M","email"=>"pricho1987@yahoo.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Sandy Febiansyakh Kurniawan","email"=>"sandykusuma09@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Jasmine","email"=>"audrianajasmine@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Revi Yanuar","email"=>"revyyanuar27@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Wan Sopian Putera","email"=>"wansopianputera150292@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Muhammad Farhan","email"=>"mfarhan552@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Salsabila Nurkholifah","email"=>"salsabilank@yahoo.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ahmad Nurzaman Sidiq","email"=>"nurzamansidiq06@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Arjuna Sirait","email"=>"arjunasiraitofficial@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Hanna Exaudia Ekasyahputri","email"=>"exaudia1@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ni Wayan Suparti","email"=>"wayansuparti411@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Wahyu Sadiyatmoko","email"=>"wahyusadiyatmoko@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Galank Gunawan","email"=>"hellosixtysix@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Pradira Destra Wijaya","email"=>"Pradestra@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Wahyu Azuri","email"=>"wahyu.azuri@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Relly Saprudin","email"=>"rellysaprudin646@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Muhammad Rafie Fadhali","email"=>"muhammadrafiefadhali@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ribka Xena Sitorus","email"=>"ribkaxena9@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Nadya Febiola","email"=>"febi@rahasiagadis.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Alfonsius Alfianus Nggubhu","email"=>"alfinnggubhu.pkl@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Erina Murdi Natha","email"=>"murdinathaerina@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Garbyiel Oicherio Marino Akharisdei Siagian","email"=>"garbyiel@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Raden Yudhistira Anggriawan Maspadani","email"=>"yudhis3008@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Budi Setiyawan","email"=>"triaskoba@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Hanifah Fauziyyah","email"=>"hanihny.business@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"I Dewa Gede Adi Wira Wijaya","email"=>"dewawirawijaya87@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Achmad Dodi Fachrudin","email"=>"adfachrudin@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Eveline Sahfitri Ovilia","email"=>"evelineovilias3@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Vira Wilistyorini","email"=>"virawtr18@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Bima Riski Ardiansyah","email"=>"bimaclx@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Veolina Gestindha Purmansyah","email"=>"ghea.gp@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Topan Maulana","email"=>"friegie1@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Arif Budhi Suryanto","email"=>"arifbudhisur@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Okky Audina Safirani","email"=>"okky.audina@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Nida Putri Shafina","email"=>"nidapshafina@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Marianus Seran","email"=>"romanriken21@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Puja Devi Anjani","email"=>"puja.devianjani@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Davina Aulia Sekarjagad","email"=>"davinaaulia815@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Hudoro Setyo Bawana","email"=>"mr.hudoro@yahoo.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Risvania Andaresta","email"=>"risvania.andrsta@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Linda Rahmadanti","email"=>"lindarahmad18@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Andika Thaselia Prahastiwi","email"=>"atprahastiwi@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Yuli Yanti Anggraeni","email"=>"yuliyantianggraeni290696@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ahmad Fiqi Purba","email"=>"ahmadfiqi975@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Lidya Gusfitri","email"=>"lidyagusfitri@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Sunardi Panjaitan","email"=>"panjaitansunardi@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Muhammad Riza Rasyad","email"=>"rizarasyad23@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Leesha Azra Tabina Himawan","email"=>"leeshaazra01@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Alitta Rizki Yanera","email"=>"alittayanera@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Fransiskus Asisi Everly Yoda","email"=>"fransiskuseverly@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Naufal Azis Kautsar","email"=>"naufalazis.na@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Rahma Adelia Nabila","email"=>"rahmadelian1211@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Fahmi Ario Sasongko","email"=>"fahmiario@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Siti Nurhayati","email"=>"nurhayatisiti2096@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Anggara Wahyu Fadeli Putra","email"=>"anggarawfp@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Arudaya Cika Pratama","email"=>"arudayaone2505@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Fitro Bagus Firmansyah","email"=>"fitrobagus.ofc@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Bella Gunawan","email"=>"Bellagunawann@yahoo.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Mega Rahayu","email"=>"megarahayura28@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Aindra Ramadhan Fajarputra","email"=>"aindraarr@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Desty Rani Birgita","email"=>"kdesty79@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Juan Felix Tampubolon","email"=>"juanfelix.tampu@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Moch Irham Tawakkal","email"=>"ikalirham04@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Farid Rifqi Mustofa","email"=>"faridrifqi.production@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Tarmuji","email"=>"supadipadi57@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Farity Setyawan Wibowo","email"=>"faritwibowo40@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Niken Andalusi","email"=>"deasysuyudi@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Rujita","email"=>"ariefrudjito063@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Willy Junisal Yuvanda","email"=>"willy.kalalo@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Taufik Rachmandani","email"=>"fikrd93@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ketut Ayu Ary Wardani","email"=>"ayuarywardani@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Rudi Rismanto","email"=>"rudyjoger002@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Satar","email"=>"satarromeo49@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ali Zaenal Abidin","email"=>"alizaenal080893@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Raisya Alianti","email"=>"raisyaalianti@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Tata Lugas Nastiti","email"=>"lugasnastiti11@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Firman Putrajati","email"=>"firmanputrajati17@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Winny","email"=>"chandrawinny@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Suciati","email"=>"suci15.work@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Tony Rahmansyah","email"=>"tonyrahmansyah949@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Gita Puspa Lestari","email"=>"gitataco@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Angie","email"=>"angiebratad@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Hafizh Rizky Khosasih","email"=>"hafizhrizkyxu@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Edi Kurniawan","email"=>"edik53572@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Priska Sicilia Amir","email"=>"laturiuwprisciliamir@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Elizabeth Aidy Putri","email"=>"contact.elizabethaidy@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Muhammad Fazar Hidayatulloh","email"=>"mfazar44@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Berlin Derisa Oktafiana","email"=>"aretakhanza0@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Yohana Garcia Lumongga Prangga Puteri","email"=>"yogarcias27@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Elizabeth Dianindra Zaralia Hadi","email"=>"elizabeth.zaralia@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Theresia Angelica Odelinada Hambur","email"=>"theresia.nada@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Priscilia Rhema Agatha Tambun","email"=>"prisciliarhemaagatha@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Thalia Chika Diandra","email"=>"thaliachika@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Novi Andriati Salim","email"=>"noviandriatisalim@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Fatih Hilmy Wilasa","email"=>"fatihhilmy.wilasa@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Rizki Azhar Nugraha","email"=>"rizkiazharnugraha@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Luh Anggi Derayanti","email"=>"derayantianggi@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Catharina Martha Ulina","email"=>"catharina.martha@karyadigitalmadani.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Kadek Chandra Purnama Dewi","email"=>"candrapurnamadewi2297@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Laras Rosdiana","email"=>"larasrosdiana28@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Silviana","email"=>"silvi.asha91@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Iskandar Yuda Kelana","email"=>"iskandaryuda.iy@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Made Wahyu Adi Saputra","email"=>"Madewahyu80@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Rico Renaldy Paliama","email"=>"jojopaliama@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Daffa Ikhsan Mustafa","email"=>"daffaikhsanmustafa123@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Agus Saputra","email"=>"agus.saputra1193@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Akhmad Haris Kurniawan","email"=>"harisenin.work@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Monika Br Perangin Angin","email"=>"Monikaperangin@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Farel Bima Ramadhan","email"=>"farelbr1@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Muhammad Farizan Afif","email"=>"mfarizanafif@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Inrid Agelia Floriana Wera","email"=>"inrid.agelia@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Dewi Rumondang Carmel Patricia","email"=>"dewi.rumondang@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Wanda Hamidah","email"=>"wandahmdh4@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Yohana Margareth Harianja","email"=>"yohanamargareth@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Riansyah Jamanudin Putra","email"=>"riansy137@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Thallia Agustien Ramah Yanti","email"=>"thalliaary@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Rio Antony","email"=>"rioantony12@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Cindy Angelica Khuana","email"=>"khuanacindy@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Anggia Kamilia Hanifah","email"=>"anggiakamilia97@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Zahra Jehan Rizanna","email"=>"zahrajehanr@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Muhammad Ridho Nawawi","email"=>"ridho.nawawi@unitedcreative.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Mulyono","email"=>"moel.mulyono97@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Syahril Syabirin","email"=>"Syahrilsyabirin51@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Sungadi","email"=>"Kalilakamila1969@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Irma Joanita","email"=>"joanita.stylo@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Rudy Supratikno","email"=>"rudy_supratikno@yahoo.co.id","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ogy Pratama","email"=>"ogyprtm420@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Putra Dev","email"=>"putradevyamin@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Elya Ketlinda Damanik","email"=>"elyaketlindadamanik@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Dinda Amalianingsih","email"=>"Dindardm_@outlook.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Salma Amira Hafidz","email"=>"salmaamirahafidz07@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Hilman Purnama","email"=>"hilmanpur@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Tri Indah Kusumawardhani","email"=>"indahkusumawardhani20@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Bentang Alif Ramadhan","email"=>"bentangalieframadhan@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Vanessa Aprilia Gontha","email"=>"vanessa.gontha@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Yuri Giantini","email"=>"yurigiant@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Saeful Husni Gustaman","email"=>"foelflea@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Romi Ramdani Sumantri","email"=>"Romibackdoor@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Puji Hestiningsih","email"=>"pujihestiningsih@outlook.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Kholis Anwar","email"=>"anw081000@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Opit Hidayatullah","email"=>"opithidayat7776@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Rismin","email"=>"rismin369@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Rohimat","email"=>"rohimat.abror@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Ridho Sukmadipraja","email"=>"ridho.sukmadipraja22@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Alya Zahirah","email"=>"alyazahirah01@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Anissa Eka Widianti","email"=>"anissaeka99@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Mahadewi Hemastustieta Hariawan","email"=>"mahadewihemastustieta@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Winandri Kusuma","email"=>"winandrikusuma25@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Adham Fitroh","email"=>"Adhamfth94@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Jamil","email"=>"jamilprabu25@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Edward Hidayat","email"=>"edwardhidayat52@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Yuliana Rahmawati","email"=>"yulianarahmawati3@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')],
            ["name"=>"Mathew Timothy Jezrael Menajang","email"=>"matthewmenajang02@gmail.com","role_id"=>Role::where('name','Staff')->first()->id,"password"=>Hash::make('BaliUnited1234')]
        ];

        foreach ($users as $user) {
            User::create($user);
        }
    }
}

